# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, ppf_sphinx ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Conda setup
      run: |
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        rm miniconda.sh
        source $HOME/miniconda/etc/profile.d/conda.sh && conda activate
        conda config --set always_yes yes --set changeps1 no
        conda update -q conda
        conda update -q --all
        conda config --append channels conda-forge
        conda env create -qf test-environment.yaml
        conda info --envs
        source activate test-environment
        conda info --envs
        pip install wheel setuptools
        pip install -r docs/requirements.txt

    # nbsphinx needs pandoc
    - uses: r-lib/actions/setup-pandoc@v1

    #    - name: Build docs
    #      run: |
    #        cd docs/
    #        ls
    #        rm -rf _build/
    #        make html -e
    #        cd ../

    - uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "source activate /home/runner/miniconda/envs/test-environment"
        build-command: "sphinx-build -b html . _build"
        docs-folder: "docs/"
        
    - name: Commit docs to gh-pages
      run: |
        git clone https://github.com/cartemic/pypbomb.git --branch gh-pages --single-branch gh-pages
        cp -r docs/_build/html/* gh-pages/
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
        
    - name: Push documentation changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
